// import { Separator } from "@/components/ui/separator";
import { Metadata } from "next";

import { Container } from "@/components/Container";
import { SidebarNav } from "../../(edit-profile)/components/sidebar-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sidebarNavItems = [
  {
    title: "Create Board",
    href: "/profile/create/post",
  },
  // {
  //   title: "Account",
  //   href: "/profile/try",
  // },
//   {
//     title: "Appearance",
//     href: "/examples/forms/appearance",
//   },
//   {
//     title: "Notifications",
//     href: "/examples/forms/notifications",
//   },
//   {
//     title: "Display",
//     href: "/examples/forms/display",
//   },
];

interface SettingsLayoutProps {
  children: React.ReactNode;
}

export default function SettingsLayout({ children }: SettingsLayoutProps) {
  return (
    <>
      <Container>
        <div className="space-y-6 py-10 pb-16">
          {/* <div className="space-y-0.5">
            <h2 className="text-2xl font-bold tracking-tight">Settings</h2>
            <p className="text-muted-foreground">
              Manage your account settings and set e-mail preferences.
            </p>
          </div> */}
          {/* <Separator className="my-6" /> */}
          <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
            <aside className="lg:w-1/5">
              <SidebarNav items={sidebarNavItems} />
            </aside>
            <div className="flex-1 lg:max-w-2xl">{children}</div>
          </div>
        </div>
      </Container>
    </>
  );
}
